version: "3.3"

services:
  mattermost:
    image: mattermost/mattermost-preview:latest
    restart: always
    extra_hosts:
      - dockerhost:127.0.0.1
    ports:
      - 8065:8065
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mattermost.rule=Host(`mattermost.elmakchi.ir`)"
      - "traefik.http.routers.mattermost.entrypoints=websecure"
      - "traefik.http.routers.mattermost.tls.certresolver=myresolver"
      - "traefik.http.services.mattermost.loadbalancer.server.port=80"
    networks:
      - traefik_reverse_proxy

  focalboard:
    image: mattermost/focalboard
    ports:
      - 8000:8000
    restart: always 
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.focalboard.rule=Host(`focalboard.elmakchi.ir`)"
      - "traefik.http.routers.focalboard.entrypoints=websecure"
      - "traefik.http.routers.focalboard.tls.certresolver=myresolver"
      - "traefik.http.services.focalboard.loadbalancer.server.port=80"
    networks:
      - traefik_reverse_proxy

networks:
  traefik_reverse_proxy:
    external: true